# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Bill Halpin
"""
gnat.reports.delivery
=========================

Report delivery targets — email (SMTP) and SharePoint (via DirectLine/Graph).

Both implement the :class:`~gnat.export.base.ExportDelivery` interface so
they can be used with the existing export pipeline as well as the report
generator.

INI configuration
-----------------
::

    [email]
    smtp_host     = smtp.office365.com
    smtp_port     = 587
    smtp_user     = reports@example.com
    smtp_password = <password>
    smtp_tls      = true
    from_address  = gnat-reports@example.com

    [sharepoint]
    # Uses the Copilot DirectLine secret if available, else requires
    # a separate Graph API app registration
    directline_secret = <secret>
    tenant_id         = <azure-tenant-id>
    client_id         = <app-client-id>
    client_secret     = <app-secret>
"""

from __future__ import annotations

import logging
import mimetypes
import smtplib
import ssl
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# EmailDelivery
# ---------------------------------------------------------------------------


class EmailDelivery:
    """
    Sends report files as email attachments via SMTP.

    Parameters
    ----------
    smtp_host : str
    smtp_port : int
    smtp_user : str
    smtp_password : str
    from_address : str
    to_addresses : list of str
    subject : str
    body_html : str, optional
        HTML body.  Plain-text fallback is auto-generated.
    use_tls : bool
        Start TLS after connect.  Default ``True``.

    Examples
    --------
    ::

        delivery = EmailDelivery.from_ini(
            to_addresses=["soc@example.com"],
            subject="Daily Threat Intel — 2024-03-21",
        )
        delivery.send(file_paths=["report.pdf", "report.html"])
    """

    def __init__(
        self,
        smtp_host: str,
        smtp_port: int,
        smtp_user: str,
        smtp_password: str,
        from_address: str,
        to_addresses: list[str],
        subject: str,
        body_html: str = "",
        use_tls: bool = True,
    ):
        self._host = smtp_host
        self._port = smtp_port
        self._user = smtp_user
        self._password = smtp_password
        self._from = from_address
        self._to = to_addresses
        self._subject = subject
        self._body_html = body_html
        self._tls = use_tls

    @classmethod
    def from_ini(
        cls,
        to_addresses: list[str],
        subject: str,
        body_html: str = "",
        config_path: str | None = None,
    ) -> EmailDelivery:
        """Load SMTP settings from the ``[email]`` INI section."""
        from gnat.config import GNATConfig

        cfg = GNATConfig(config_path)
        try:
            s = cfg.get("email")
        except KeyError:
            raise KeyError(
                "No [email] section in config.ini. Add:\n"
                "  [email]\n"
                "  smtp_host = smtp.office365.com\n"
                "  smtp_port = 587\n"
                "  smtp_user = user@example.com\n"
                "  smtp_password = <password>\n"
                "  from_address = reports@example.com\n"
            )
        return cls(
            smtp_host=s.get("smtp_host", "localhost"),
            smtp_port=int(s.get("smtp_port", 587)),
            smtp_user=s.get("smtp_user", ""),
            smtp_password=s.get("smtp_password", ""),
            from_address=s.get("from_address", s.get("smtp_user", "")),
            to_addresses=to_addresses,
            subject=subject,
            body_html=body_html,
            use_tls=s.get("smtp_tls", "true").lower() == "true",
        )

    def send(self, file_paths: list[str]) -> dict[str, Any]:
        """
        Send report files as attachments.

        Parameters
        ----------
        file_paths : list of str
            Local paths of files to attach.

        Returns
        -------
        dict
            ``{"success": bool, "recipients": [...], "error": str or None}``
        """
        msg = MIMEMultipart("mixed")
        msg["From"] = self._from
        msg["To"] = ", ".join(self._to)
        msg["Subject"] = self._subject

        # Body
        body_text = "Please find the attached threat intelligence report.\n\nGenerated by GNAT."
        alt = MIMEMultipart("alternative")
        alt.attach(MIMEText(body_text, "plain"))
        if self._body_html:
            alt.attach(MIMEText(self._body_html, "html"))
        msg.attach(alt)

        # Attachments
        attached = []
        for fp in file_paths:
            p = Path(fp)
            if not p.exists():
                logger.warning("EmailDelivery: file not found: %s", fp)
                continue
            mime_type, _ = mimetypes.guess_type(str(p))
            _, _ = (mime_type or "application/octet-stream").split("/", 1)
            with open(p, "rb") as f:
                part = MIMEApplication(f.read(), Name=p.name)
                part["Content-Disposition"] = f'attachment; filename="{p.name}"'
                msg.attach(part)
                attached.append(p.name)

        try:
            if self._tls:
                context = ssl.create_default_context()
                with smtplib.SMTP(self._host, self._port) as server:
                    server.ehlo()
                    server.starttls(context=context)
                    server.login(self._user, self._password)
                    server.sendmail(self._from, self._to, msg.as_string())
            else:
                with smtplib.SMTP(self._host, self._port) as server:
                    server.login(self._user, self._password)
                    server.sendmail(self._from, self._to, msg.as_string())

            logger.info(
                "EmailDelivery: sent to %s with %d attachment(s): %s",
                self._to,
                len(attached),
                attached,
            )
            return {"success": True, "recipients": self._to, "error": None, "attachments": attached}

        except smtplib.SMTPException as exc:
            logger.error("EmailDelivery: SMTP error — %s", exc)
            return {"success": False, "recipients": self._to, "error": str(exc), "attachments": []}


# ---------------------------------------------------------------------------
# SharePointDelivery
# ---------------------------------------------------------------------------


class SharePointDelivery:
    """
    Uploads report files to a SharePoint document library via the
    Microsoft Graph API.

    Two authentication modes:

    **Client credentials** (server-to-server, recommended for automation):
    App registration in Azure AD with ``Files.ReadWrite.All`` permission.
    Configure ``tenant_id``, ``client_id``, and ``client_secret`` in INI.

    **DirectLine proxy** (reuses Copilot infrastructure):
    Uses the Bot Framework DirectLine connection from ``[copilot]``
    to instruct Copilot to save files. Simpler to configure but relies
    on the Copilot bot having write access to SharePoint.

    Parameters
    ----------
    site_url : str
        Full SharePoint site URL, e.g.
        ``"https://contoso.sharepoint.com/sites/Security"``.
    library_path : str
        Library name or relative path within the site, e.g.
        ``"Threat Reports"``.
    tenant_id : str, optional
        Azure tenant id for client-credentials auth.
    client_id : str, optional
        App registration client id.
    client_secret : str, optional
        App registration client secret.
    folder : str, optional
        Subfolder within the library to upload to.
        Auto-created if it does not exist.

    Examples
    --------
    ::

        sp = SharePointDelivery.from_ini(
            site_url="https://contoso.sharepoint.com/sites/Security",
            library_path="Threat Reports",
        )
        result = sp.upload(file_paths=["report.pdf", "report.docx"])
    """

    def __init__(
        self,
        site_url: str,
        library_path: str,
        tenant_id: str = "",
        client_id: str = "",
        client_secret: str = "",
        folder: str = "",
    ):
        self._site_url = site_url.rstrip("/")
        self._library_path = library_path
        self._tenant_id = tenant_id
        self._client_id = client_id
        self._client_secret = client_secret
        self._folder = folder

    @classmethod
    def from_ini(
        cls,
        site_url: str,
        library_path: str,
        folder: str = "",
        config_path: str | None = None,
    ) -> SharePointDelivery:
        """Load Graph API credentials from the ``[sharepoint]`` INI section."""
        from gnat.config import GNATConfig

        cfg = GNATConfig(config_path)
        try:
            s = cfg.get("sharepoint")
        except KeyError:
            raise KeyError(
                "No [sharepoint] section in config.ini. Add:\n"
                "  [sharepoint]\n"
                "  tenant_id     = <azure-tenant-id>\n"
                "  client_id     = <app-client-id>\n"
                "  client_secret = <app-secret>\n"
            )
        return cls(
            site_url=site_url,
            library_path=library_path,
            tenant_id=s.get("tenant_id", ""),
            client_id=s.get("client_id", ""),
            client_secret=s.get("client_secret", ""),
            folder=folder,
        )

    def upload(self, file_paths: list[str]) -> dict[str, Any]:
        """
        Upload files to SharePoint.

        Parameters
        ----------
        file_paths : list of str
            Local file paths to upload.

        Returns
        -------
        dict
            ``{"success": bool, "uploaded": [...], "urls": [...], "error": str or None}``
        """
        token = self._get_access_token()
        if not token:
            return {
                "success": False,
                "uploaded": [],
                "urls": [],
                "error": "Failed to obtain access token",
            }

        site_id = self._get_site_id(token)
        if not site_id:
            return {
                "success": False,
                "uploaded": [],
                "urls": [],
                "error": f"Could not resolve site id for {self._site_url}",
            }

        drive_id = self._get_drive_id(token, site_id)
        if not drive_id:
            return {
                "success": False,
                "uploaded": [],
                "urls": [],
                "error": "Could not find document library drive",
            }

        uploaded = []
        urls = []
        errors = []

        for fp in file_paths:
            p = Path(fp)
            if not p.exists():
                errors.append(f"File not found: {fp}")
                continue
            try:
                url = self._upload_file(token, drive_id, p)
                if url:
                    uploaded.append(p.name)
                    urls.append(url)
                    logger.info("SharePointDelivery: uploaded %s → %s", p.name, url)
                else:
                    errors.append(f"Upload returned no URL for {p.name}")
            except Exception as exc:
                errors.append(f"{p.name}: {exc}")
                logger.error("SharePointDelivery: upload error for %s — %s", p.name, exc)

        success = len(uploaded) > 0 and not errors
        return {
            "success": success,
            "uploaded": uploaded,
            "urls": urls,
            "error": "; ".join(errors) if errors else None,
        }

    # ── Graph API helpers ──────────────────────────────────────────────────

    def _get_access_token(self) -> str | None:
        """Obtain an OAuth2 client-credentials token from Azure AD."""
        import urllib.parse
        import urllib.request

        if not all([self._tenant_id, self._client_id, self._client_secret]):
            logger.error("SharePointDelivery: missing tenant_id/client_id/client_secret")
            return None

        url = f"https://login.microsoftonline.com/{self._tenant_id}/oauth2/v2.0/token"
        data = urllib.parse.urlencode(
            {
                "grant_type": "client_credentials",
                "client_id": self._client_id,
                "client_secret": self._client_secret,
                "scope": "https://graph.microsoft.com/.default",
            }
        ).encode()

        try:
            import json as _json

            req = urllib.request.Request(url, data=data, method="POST")
            with urllib.request.urlopen(req, timeout=30) as resp:  # nosec B310  # nosemgrep
                result = _json.loads(resp.read())
                return result.get("access_token")
        except Exception as exc:
            logger.error("SharePointDelivery: token error — %s", exc)  # nosemgrep
            return None

    def _graph_get(self, token: str, path: str) -> dict | None:
        import json as _json
        import urllib.request

        url = f"https://graph.microsoft.com/v1.0{path}"
        req = urllib.request.Request(
            url,
            headers={"Authorization": f"Bearer {token}"},
        )
        try:
            with urllib.request.urlopen(req, timeout=30) as resp:  # nosec B310  # nosemgrep
                return _json.loads(resp.read())
        except Exception as exc:
            logger.debug("SharePointDelivery: GET %s → %s", path, exc)
            return None

    def _get_site_id(self, token: str) -> str | None:
        """Resolve SharePoint site URL to a Graph site id."""
        from urllib.parse import urlparse

        parsed = urlparse(self._site_url)
        hostname = parsed.netloc
        path = parsed.path.strip("/")
        result = self._graph_get(token, f"/sites/{hostname}:/{path}")
        return result.get("id") if result else None

    def _get_drive_id(self, token: str, site_id: str) -> str | None:
        """Get the document library drive id."""
        result = self._graph_get(token, f"/sites/{site_id}/drives")
        if not result:
            return None
        drives = result.get("value", [])
        # Find drive matching library_path
        for drive in drives:
            if drive.get("name", "").lower() == self._library_path.lower() or drive.get(
                "webUrl", ""
            ).endswith(self._library_path.replace(" ", "%20")):
                return drive["id"]
        # Fall back to default drive
        return drives[0]["id"] if drives else None

    def _upload_file(self, token: str, drive_id: str, file_path: Path) -> str | None:
        """Upload one file via Graph DriveItem PUT."""
        import urllib.request

        dest_folder = self._folder or ""
        if dest_folder:
            item_path = f"/{dest_folder}/{file_path.name}"
        else:
            item_path = f"/{file_path.name}"

        url = f"https://graph.microsoft.com/v1.0/drives/{drive_id}/root:{item_path}:/content"
        data = file_path.read_bytes()
        mime, _ = mimetypes.guess_type(str(file_path))
        req = urllib.request.Request(
            url,
            data=data,
            headers={
                "Authorization": f"Bearer {token}",
                "Content-Type": mime or "application/octet-stream",
            },
            method="PUT",
        )
        try:
            import json as _json

            with urllib.request.urlopen(req, timeout=120) as resp:  # nosec B310  # nosemgrep
                result = _json.loads(resp.read())
                return result.get("webUrl")
        except Exception as exc:
            raise RuntimeError(f"Graph upload failed: {exc}") from exc
