"""
gnat.reports.renderers
==========================

Four report renderers — Markdown, HTML, PDF, DOCX — all consuming the
same :class:`~gnat.reports.base.ReportDocument` intermediate structure.

Architecture
------------
Markdown is the canonical intermediate format.  HTML is generated from
it using a lightweight template (no external Markdown parser required —
the document structure is simple enough to generate HTML directly).
PDF is generated via ``reportlab`` (stdlib-compatible, no subprocess).
DOCX is generated via a Node.js script using the ``docx`` npm package
(following the skill recommendations).

All renderers write to a file path and return that path.
"""

from __future__ import annotations

import json
import logging
import os
import subprocess
import tempfile
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from gnat.reports.base import ReportDocument, ReportSection

logger = logging.getLogger(__name__)

# Colour palette for HTML/PDF
_COLOURS = {
    "primary":    "#1a3a5c",   # dark navy
    "accent":     "#2e75b6",   # steel blue
    "warning":    "#c55a11",   # amber
    "critical":   "#c00000",   # red
    "light_bg":   "#f5f7fa",
    "border":     "#d0d7de",
    "text":       "#1f2937",
    "muted":      "#6b7280",
}


# ---------------------------------------------------------------------------
# MarkdownRenderer
# ---------------------------------------------------------------------------

class MarkdownRenderer:
    """Renders a ReportDocument to Markdown."""

    def render(self, doc: "ReportDocument", path: str) -> str:
        md = self._build(doc)
        Path(path).write_text(md, encoding="utf-8")
        logger.info("MarkdownRenderer: wrote %s", path)
        return path

    def render_string(self, doc: "ReportDocument") -> str:
        return self._build(doc)

    def _build(self, doc: "ReportDocument") -> str:
        lines = []
        lines.append(f"# {doc.title}")
        lines.append(f"")
        lines.append(f"**Report Type:** {doc.report_type.title()}  ")
        lines.append(f"**Generated:** {doc.generated_at.strftime('%Y-%m-%d %H:%M UTC')}  ")
        lines.append(f"**Period:** {doc.period_start.strftime('%Y-%m-%d')} "
                     f"to {doc.period_end.strftime('%Y-%m-%d')}  ")
        if doc.config and doc.config.sectors:
            lines.append(f"**Sectors:** {', '.join(doc.config.sectors)}  ")
        lines.append("")
        lines.append("---")
        lines.append("")

        for section in doc.sections:
            lines.append(f"## {section.title}")
            lines.append("")

            if section.has_narrative:
                lines.append(section.narrative)
                lines.append("")

            if section.has_data:
                for sub in _render_data_md(section):
                    lines.append(sub)
                lines.append("")

        lines.append("---")
        lines.append(f"*Generated by GNAT threat intelligence platform*")

        return "\n".join(lines)


# ---------------------------------------------------------------------------
# HTMLRenderer
# ---------------------------------------------------------------------------

class HTMLRenderer:
    """Renders a ReportDocument to a self-contained HTML file."""

    def render(self, doc: "ReportDocument", path: str) -> str:
        html = self._build(doc)
        Path(path).write_text(html, encoding="utf-8")
        logger.info("HTMLRenderer: wrote %s", path)
        return path

    def _build(self, doc: "ReportDocument") -> str:
        sections_html = "\n".join(self._section_html(s) for s in doc.sections)
        sector_badge = ""
        if doc.config and doc.config.sectors:
            badges = "".join(
                f'<span class="badge">{s}</span>'
                for s in doc.config.sectors[:6]
            )
            sector_badge = f'<div class="sector-badges">{badges}</div>'

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{_esc(doc.title)}</title>
<style>
  :root {{
    --primary: {_COLOURS["primary"]};
    --accent:  {_COLOURS["accent"]};
    --warn:    {_COLOURS["warning"]};
    --crit:    {_COLOURS["critical"]};
    --bg:      {_COLOURS["light_bg"]};
    --border:  {_COLOURS["border"]};
    --text:    {_COLOURS["text"]};
    --muted:   {_COLOURS["muted"]};
  }}
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: Arial, Helvetica, sans-serif; font-size: 14px;
          color: var(--text); background: #fff; line-height: 1.6; }}
  .container {{ max-width: 960px; margin: 0 auto; padding: 32px 24px; }}
  .report-header {{ background: var(--primary); color: #fff;
                    padding: 32px; margin-bottom: 24px; border-radius: 4px; }}
  .report-header h1 {{ font-size: 28px; font-weight: 700; margin-bottom: 8px; }}
  .report-meta {{ font-size: 12px; opacity: 0.8; line-height: 2; }}
  .sector-badges {{ margin-top: 12px; }}
  .badge {{ display: inline-block; background: rgba(255,255,255,0.2);
            padding: 2px 10px; border-radius: 12px; font-size: 11px;
            margin-right: 6px; margin-top: 4px; }}
  .section {{ margin-bottom: 32px; padding: 24px; border: 1px solid var(--border);
              border-radius: 4px; background: #fff; }}
  .section h2 {{ font-size: 18px; color: var(--primary); margin-bottom: 16px;
                 padding-bottom: 8px; border-bottom: 2px solid var(--accent); }}
  .narrative {{ line-height: 1.8; margin-bottom: 16px; color: var(--text); }}
  .narrative p {{ margin-bottom: 12px; }}
  table {{ width: 100%; border-collapse: collapse; margin-top: 12px;
           font-size: 13px; }}
  th {{ background: var(--primary); color: #fff; padding: 8px 12px;
        text-align: left; font-weight: 600; }}
  td {{ padding: 7px 12px; border-bottom: 1px solid var(--border); }}
  tr:nth-child(even) {{ background: var(--bg); }}
  tr:hover {{ background: #e8f0fe; }}
  .stat-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));
                gap: 16px; margin-top: 12px; }}
  .stat-card {{ background: var(--bg); border: 1px solid var(--border);
                padding: 16px; border-radius: 4px; text-align: center; }}
  .stat-card .value {{ font-size: 28px; font-weight: 700; color: var(--accent); }}
  .stat-card .label {{ font-size: 11px; color: var(--muted); margin-top: 4px; }}
  .tag-critical {{ color: var(--crit); font-weight: 600; }}
  .tag-high     {{ color: var(--warn); font-weight: 600; }}
  .footer {{ margin-top: 40px; text-align: center; font-size: 11px;
             color: var(--muted); border-top: 1px solid var(--border); padding-top: 16px; }}
</style>
</head>
<body>
<div class="container">
  <div class="report-header">
    <h1>{_esc(doc.title)}</h1>
    <div class="report-meta">
      <strong>Type:</strong> {doc.report_type.title()} &nbsp;|&nbsp;
      <strong>Generated:</strong> {doc.generated_at.strftime('%Y-%m-%d %H:%M UTC')} &nbsp;|&nbsp;
      <strong>Period:</strong> {doc.period_start.strftime('%Y-%m-%d')} to
        {doc.period_end.strftime('%Y-%m-%d')}
    </div>
    {sector_badge}
  </div>

  {sections_html}

  <div class="footer">Generated by GNAT Threat Intelligence Platform</div>
</div>
</body>
</html>"""

    def _section_html(self, section: "ReportSection") -> str:
        narrative_html = ""
        if section.has_narrative:
            paragraphs = [
                f"<p>{_esc(p)}</p>"
                for p in section.narrative.split("\n\n")
                if p.strip()
            ]
            narrative_html = (
                f'<div class="narrative">{"".join(paragraphs)}</div>'
            )

        data_html = _render_data_html(section)

        return f"""<div class="section">
  <h2>{_esc(section.title)}</h2>
  {narrative_html}
  {data_html}
</div>"""


# ---------------------------------------------------------------------------
# PDFRenderer
# ---------------------------------------------------------------------------

class PDFRenderer:
    """Renders a ReportDocument to PDF using reportlab."""

    def render(self, doc: "ReportDocument", path: str) -> str:
        try:
            from reportlab.lib.pagesizes import letter
            from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
            from reportlab.lib.units import inch
            from reportlab.lib import colors
            from reportlab.platypus import (
                SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
                HRFlowable, PageBreak,
            )
        except ImportError:
            raise ImportError(
                "reportlab required for PDF output: "
                "pip install 'gnat[reports]'"
            )

        Path(path).parent.mkdir(parents=True, exist_ok=True)
        pdf = SimpleDocTemplate(
            path,
            pagesize=letter,
            rightMargin=inch,
            leftMargin=inch,
            topMargin=inch,
            bottomMargin=inch,
            title=doc.title,
            author="GNAT",
        )

        styles = getSampleStyleSheet()

        # Custom styles
        primary_rgb = colors.HexColor(_COLOURS["primary"])
        accent_rgb  = colors.HexColor(_COLOURS["accent"])

        title_style = ParagraphStyle(
            "ReportTitle",
            parent=styles["Title"],
            textColor=primary_rgb,
            fontSize=22,
            spaceAfter=6,
            fontName="Helvetica-Bold",
        )
        h2_style = ParagraphStyle(
            "SectionHead",
            parent=styles["Heading2"],
            textColor=primary_rgb,
            fontSize=14,
            spaceBefore=16,
            spaceAfter=8,
            fontName="Helvetica-Bold",
        )
        meta_style = ParagraphStyle(
            "Meta",
            parent=styles["Normal"],
            fontSize=9,
            textColor=colors.HexColor(_COLOURS["muted"]),
            spaceAfter=4,
        )
        body_style = ParagraphStyle(
            "Body",
            parent=styles["Normal"],
            fontSize=10,
            leading=16,
            spaceAfter=8,
            fontName="Helvetica",
        )

        story = []

        # Title block
        story.append(Paragraph(_safe_rl(doc.title), title_style))
        story.append(Paragraph(
            f"Report Type: {doc.report_type.title()}  |  "
            f"Generated: {doc.generated_at.strftime('%Y-%m-%d %H:%M UTC')}",
            meta_style,
        ))
        story.append(Paragraph(
            f"Period: {doc.period_start.strftime('%Y-%m-%d')} to "
            f"{doc.period_end.strftime('%Y-%m-%d')}",
            meta_style,
        ))
        if doc.config and doc.config.sectors:
            story.append(Paragraph(
                "Sectors: " + ", ".join(doc.config.sectors[:6]),
                meta_style,
            ))
        story.append(HRFlowable(
            width="100%", thickness=2, color=accent_rgb, spaceAfter=16
        ))

        # Sections
        for section in doc.sections:
            story.append(Paragraph(_safe_rl(section.title), h2_style))
            story.append(HRFlowable(
                width="100%", thickness=0.5,
                color=colors.HexColor(_COLOURS["border"]),
                spaceAfter=8,
            ))

            if section.has_narrative:
                for para in section.narrative.split("\n\n"):
                    if para.strip():
                        story.append(Paragraph(_safe_rl(para.strip()), body_style))
                story.append(Spacer(1, 8))

            # Data tables for key section types
            table_items = _extract_table_items(section)
            if table_items:
                for tbl_data, col_widths in table_items:
                    tbl = Table(tbl_data, colWidths=col_widths)
                    tbl.setStyle(TableStyle([
                        ("BACKGROUND",  (0, 0), (-1, 0), primary_rgb),
                        ("TEXTCOLOR",   (0, 0), (-1, 0), colors.white),
                        ("FONTNAME",    (0, 0), (-1, 0), "Helvetica-Bold"),
                        ("FONTSIZE",    (0, 0), (-1, -1), 9),
                        ("ROWBACKGROUNDS", (0, 1), (-1, -1),
                         [colors.white, colors.HexColor(_COLOURS["light_bg"])]),
                        ("GRID",        (0, 0), (-1, -1), 0.5,
                         colors.HexColor(_COLOURS["border"])),
                        ("VALIGN",      (0, 0), (-1, -1), "TOP"),
                        ("PADDING",     (0, 0), (-1, -1), 6),
                    ]))
                    story.append(tbl)
                    story.append(Spacer(1, 12))

        story.append(HRFlowable(width="100%", thickness=0.5,
                                 color=colors.grey, spaceAfter=6))
        story.append(Paragraph(
            "Generated by GNAT Threat Intelligence Platform",
            ParagraphStyle("Footer", parent=styles["Normal"],
                           fontSize=8, textColor=colors.grey,
                           alignment=1),  # centre
        ))

        pdf.build(story)
        logger.info("PDFRenderer: wrote %s", path)
        return path


# ---------------------------------------------------------------------------
# DOCXRenderer
# ---------------------------------------------------------------------------

class DOCXRenderer:
    """Renders a ReportDocument to DOCX using docx (Node.js npm package)."""

    def render(self, doc: "ReportDocument", path: str) -> str:
        Path(path).parent.mkdir(parents=True, exist_ok=True)
        script = self._build_script(doc, path)
        with tempfile.NamedTemporaryFile(
            suffix=".js", delete=False, mode="w", encoding="utf-8"
        ) as f:
            f.write(script)
            script_path = f.name

        try:
            result = subprocess.run(
                ["node", script_path],
                capture_output=True,
                text=True,
                timeout=60,
            )
            if result.returncode != 0:
                raise RuntimeError(
                    f"DOCX generation failed: {result.stderr[:500]}"
                )
        finally:
            os.unlink(script_path)

        logger.info("DOCXRenderer: wrote %s", path)
        return path

    def _build_script(self, doc: "ReportDocument", out_path: str) -> str:
        sections_js = ",\n".join(
            self._section_to_js(s) for s in doc.sections
        )
        sector_text = (
            "Sectors: " + ", ".join(doc.config.sectors[:6])
            if doc.config and doc.config.sectors else ""
        )
        title      = _js_str(doc.title)
        gen_date   = _js_str(doc.generated_at.strftime("%Y-%m-%d %H:%M UTC"))
        period     = _js_str(
            f"{doc.period_start.strftime('%Y-%m-%d')} to "
            f"{doc.period_end.strftime('%Y-%m-%d')}"
        )
        sector_js  = _js_str(sector_text)
        out_js     = _js_str(str(Path(out_path).resolve()))

        return f"""
const {{ Document, Packer, Paragraph, TextRun, Table, TableRow,
         TableCell, HeadingLevel, AlignmentType, BorderStyle,
         WidthType, ShadingType, LevelFormat }} = require('docx');
const fs = require('fs');

const PRIMARY = "1A3A5C";
const ACCENT  = "2E75B6";
const BORDER  = {{ style: BorderStyle.SINGLE, size: 1, color: "D0D7DE" }};
const BORDERS = {{ top: BORDER, bottom: BORDER, left: BORDER, right: BORDER }};
const CELL_W  = {{ size: 4680, type: WidthType.DXA }};

function header(text, level) {{
  return new Paragraph({{
    heading: level,
    children: [new TextRun({{ text, bold: true, color: PRIMARY,
      size: level === HeadingLevel.HEADING_1 ? 36 : 28 }})]
  }});
}}

function body(text) {{
  return text.split("\\n\\n").filter(p => p.trim()).map(p =>
    new Paragraph({{ children: [new TextRun({{ text: p.trim(), size: 20 }})],
      spacing: {{ after: 120 }} }})
  );
}}

function hr() {{
  return new Paragraph({{
    border: {{ bottom: {{ style: BorderStyle.SINGLE, size: 6, color: ACCENT, space: 1 }} }},
    spacing: {{ after: 160 }}
  }});
}}

function metaLine(label, value) {{
  return new Paragraph({{
    children: [
      new TextRun({{ text: label + ": ", bold: true, size: 18, color: "6B7280" }}),
      new TextRun({{ text: value, size: 18, color: "6B7280" }})
    ],
    spacing: {{ after: 40 }}
  }});
}}

function simpleTable(rows, headers) {{
  return new Table({{
    width: {{ size: 9360, type: WidthType.DXA }},
    columnWidths: Array(headers.length).fill(Math.floor(9360 / headers.length)),
    rows: [
      new TableRow({{
        children: headers.map(h => new TableCell({{
          borders: BORDERS,
          width: CELL_W,
          margins: {{ top: 80, bottom: 80, left: 120, right: 120 }},
          shading: {{ fill: PRIMARY, type: ShadingType.CLEAR }},
          children: [new Paragraph({{ children: [new TextRun({{
            text: h, bold: true, color: "FFFFFF", size: 18
          }})] }})]
        }}))
      }}),
      ...rows.map((row, i) => new TableRow({{
        children: row.map(cell => new TableCell({{
          borders: BORDERS,
          width: CELL_W,
          margins: {{ top: 80, bottom: 80, left: 120, right: 120 }},
          shading: {{ fill: i % 2 === 0 ? "FFFFFF" : "F5F7FA", type: ShadingType.CLEAR }},
          children: [new Paragraph({{ children: [new TextRun({{
            text: String(cell), size: 18
          }})] }})]
        }}))
      }}))
    ]
  }});
}}

const children = [
  header({title}, HeadingLevel.HEADING_1),
  metaLine("Report Type", {_js_str(doc.report_type.title())}),
  metaLine("Generated", {gen_date}),
  metaLine("Period", {period}),
  {f'metaLine("Sectors", {sector_js}),' if sector_text else ''}
  hr(),
  {sections_js}
  new Paragraph({{
    children: [new TextRun({{ text: "Generated by GNAT Threat Intelligence Platform",
      size: 16, color: "9CA3AF", italics: true }})],
    alignment: AlignmentType.CENTER,
    spacing: {{ before: 400 }}
  }})
];

const doc = new Document({{
  styles: {{
    default: {{ document: {{ run: {{ font: "Arial", size: 20 }} }} }},
    paragraphStyles: [
      {{ id: "Heading1", name: "Heading 1", basedOn: "Normal", next: "Normal", quickFormat: true,
        run: {{ size: 36, bold: true, font: "Arial" }},
        paragraph: {{ spacing: {{ before: 240, after: 240 }}, outlineLevel: 0 }} }},
      {{ id: "Heading2", name: "Heading 2", basedOn: "Normal", next: "Normal", quickFormat: true,
        run: {{ size: 28, bold: true, font: "Arial" }},
        paragraph: {{ spacing: {{ before: 180, after: 120 }}, outlineLevel: 1 }} }},
    ]
  }},
  sections: [{{
    properties: {{
      page: {{
        size: {{ width: 12240, height: 15840 }},
        margin: {{ top: 1440, right: 1440, bottom: 1440, left: 1440 }}
      }}
    }},
    children
  }}]
}});

Packer.toBuffer(doc).then(buf => {{
  fs.writeFileSync({out_js}, buf);
  console.log("DOCX written:", {out_js});
}}).catch(err => {{ console.error(err); process.exit(1); }});
"""

    def _section_to_js(self, section: "ReportSection") -> str:
        parts = [
            f"  header({_js_str(section.title)}, HeadingLevel.HEADING_2),"
        ]

        if section.has_narrative:
            parts.append(f"  ...body({_js_str(section.narrative)}),")

        # Simple data table for top-N lists
        data = section.data
        if "top_actors" in data and data["top_actors"]:
            rows = [
                [a.get("name", ""), ", ".join(a.get("motivation", []))[:40]]
                for a in data["top_actors"][:8]
            ]
            rows_js = json.dumps(rows)
            parts.append(
                f"  simpleTable({rows_js}, ['Threat Actor', 'Motivation']),"
            )
        elif "critical_vulns" in data and data["critical_vulns"]:
            rows = [
                [
                    v.get("cve_id") or v.get("name", ""),
                    str(v.get("cvss", "N/A")),
                    "Yes" if v.get("exploited") else "No",
                ]
                for v in data["critical_vulns"][:10]
            ]
            rows_js = json.dumps(rows)
            parts.append(
                f"  simpleTable({rows_js}, ['CVE', 'CVSS', 'Exploited']),"
            )
        elif "ioc_by_type" in data and data["ioc_by_type"]:
            rows = [[k, str(v)] for k, v in list(data["ioc_by_type"].items())[:8]]
            rows_js = json.dumps(rows)
            parts.append(f"  simpleTable({rows_js}, ['IOC Type', 'Count']),")

        return "\n".join(parts)


# ---------------------------------------------------------------------------
# Shared data rendering helpers
# ---------------------------------------------------------------------------

def _render_data_md(section: "ReportSection") -> List[str]:
    """Render section data as Markdown table(s)."""
    lines = []
    data = section.data

    def _table(headers, rows):
        lines.append("| " + " | ".join(headers) + " |")
        lines.append("| " + " | ".join(["---"] * len(headers)) + " |")
        for row in rows:
            lines.append("| " + " | ".join(str(c) for c in row) + " |")
        lines.append("")

    if "top_actors" in data and data["top_actors"]:
        lines.append("**Top Threat Actors**")
        _table(
            ["Name", "Motivation"],
            [[a["name"], ", ".join(a.get("motivation", []))[:60]]
             for a in data["top_actors"][:8]]
        )
    if "critical_vulns" in data and data["critical_vulns"]:
        lines.append("**Critical Vulnerabilities**")
        _table(
            ["CVE / Name", "CVSS", "Exploited"],
            [[v.get("cve_id") or v.get("name", ""),
              v.get("cvss", "N/A"),
              "✓" if v.get("exploited") else ""]
             for v in data["critical_vulns"][:10]]
        )
    if "ioc_by_type" in data and data["ioc_by_type"]:
        lines.append("**IOC Type Breakdown**")
        _table(
            ["Type", "Count"],
            [[k, v] for k, v in list(data["ioc_by_type"].items())[:8]]
        )
    if "sector_distribution" in data and data["sector_distribution"]:
        lines.append("**Sector Distribution**")
        _table(
            ["Sector", "Object Count"],
            [[k, v] for k, v in list(data["sector_distribution"].items())[:8]]
        )
    if "source_breakdown" in data and data["source_breakdown"]:
        lines.append("**Source Breakdown**")
        _table(
            ["Source", "Objects"],
            [[k, v] for k, v in list(data["source_breakdown"].items())[:8]]
        )
    return lines


def _render_data_html(section: "ReportSection") -> str:
    """Render section data as HTML tables and stat cards."""
    parts = []
    data = section.data

    # Stat cards for summary sections
    stats = {}
    if "total_new" in data:
        stats["New Objects"] = data["total_new"]
    if "total_objects" in data:
        stats["Total Objects"] = data["total_objects"]

    if stats:
        cards = "".join(
            f'<div class="stat-card">'
            f'<div class="value">{v}</div>'
            f'<div class="label">{k}</div>'
            f'</div>'
            for k, v in stats.items()
        )
        parts.append(f'<div class="stat-grid">{cards}</div>')

    def _html_table(headers, rows, caption=""):
        hdr = "".join(f"<th>{_esc(h)}</th>" for h in headers)
        body_rows = "".join(
            "<tr>" + "".join(f"<td>{_esc(str(c))}</td>" for c in row) + "</tr>"
            for row in rows
        )
        cap = f"<caption style='text-align:left;font-weight:600;margin-bottom:6px'>{_esc(caption)}</caption>" if caption else ""
        return f"<table>{cap}<thead><tr>{hdr}</tr></thead><tbody>{body_rows}</tbody></table>"

    if "top_actors" in data and data["top_actors"]:
        parts.append(_html_table(
            ["Threat Actor", "Motivation"],
            [[a["name"], ", ".join(a.get("motivation", []))[:60]]
             for a in data["top_actors"][:8]],
            "Top Threat Actors",
        ))
    if "critical_vulns" in data and data["critical_vulns"]:
        parts.append(_html_table(
            ["CVE / Name", "CVSS", "Exploited"],
            [[v.get("cve_id") or v.get("name", ""),
              v.get("cvss", "N/A"),
              "Yes" if v.get("exploited") else "No"]
             for v in data["critical_vulns"][:10]],
            "Critical Vulnerabilities",
        ))
    if "ioc_by_type" in data and data["ioc_by_type"]:
        parts.append(_html_table(
            ["IOC Type", "Count"],
            list(data["ioc_by_type"].items())[:8],
            "IOC Type Breakdown",
        ))
    if "sector_distribution" in data and data["sector_distribution"]:
        parts.append(_html_table(
            ["Sector", "Objects"],
            list(data["sector_distribution"].items())[:8],
            "Sector Distribution",
        ))

    return "\n".join(parts)


def _extract_table_items(section: "ReportSection"):
    """Extract (table_data, col_widths) tuples for PDF rendering."""
    from reportlab.lib.units import inch
    items = []
    data = section.data

    if "top_actors" in data and data["top_actors"]:
        rows = [["Threat Actor", "Motivation"]]
        rows += [[a["name"][:40], ", ".join(a.get("motivation", []))[:40]]
                 for a in data["top_actors"][:8]]
        items.append((rows, [3 * inch, 3 * inch]))

    if "critical_vulns" in data and data["critical_vulns"]:
        rows = [["CVE / Name", "CVSS", "Exploited"]]
        rows += [
            [v.get("cve_id") or v.get("name", "")[:40],
             str(v.get("cvss", "N/A")),
             "Yes" if v.get("exploited") else "No"]
            for v in data["critical_vulns"][:10]
        ]
        items.append((rows, [3 * inch, 1 * inch, 1 * inch]))

    if "ioc_by_type" in data and data["ioc_by_type"]:
        rows = [["IOC Type", "Count"]]
        rows += list(data["ioc_by_type"].items())[:8]
        items.append((rows, [3 * inch, 2 * inch]))

    return items


def _esc(text: str) -> str:
    """HTML-escape a string."""
    return (
        str(text)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def _safe_rl(text: str) -> str:
    """Escape for ReportLab Paragraph (strip XML-unsafe chars)."""
    return (
        str(text)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


def _js_str(s: str) -> str:
    """Escape a Python string for safe embedding in a JS string literal."""
    s = str(s)
    s = s.replace("\\", "\\\\")
    s = s.replace('"', '\\"')
    s = s.replace("\n", "\\n")
    s = s.replace("\r", "")
    return f'"{s}"'
