"""
gnat.connectors.sentinel.alerts
=====================================
Alert management commands for Microsoft Sentinel.
Alerts are generated by analytic rules and aggregated into incidents.
"""

from .client import SentinelClient


class SentinelAlertCommands:
    """Alert query operations."""

    def __init__(self, client: SentinelClient) -> None:
        self._client = client

    def list_alerts(
        self,
        filter_val: str | None = None,
        limit: int | None = None,
    ) -> list[dict]:
        """
        List security alerts.

        Parameters
        ----------
        filter_val : str | None
            OData $filter expression.
        limit : int | None
            Max results.

        Returns
        -------
        list[dict]
        """
        params: dict = {}
        if filter_val:
            params["$filter"] = filter_val
        items = []
        for item in self._client.paginate("alerts", params=params):
            items.append(item)
            if limit and len(items) >= limit:
                break
        return items

    def get_incident_alerts(self, incident_id: str) -> list[dict]:
        """
        List all alerts associated with an incident.

        Parameters
        ----------
        incident_id : str
            Sentinel incident name/ID.

        Returns
        -------
        list[dict]
        """
        result = self._client.post(f"incidents/{incident_id}/alerts")
        return result.get("value", [])

    @staticmethod
    def normalise_alert(alert: dict) -> dict:
        """Flatten a Sentinel alert to GNAT normalised format."""
        props = alert.get("properties", {})
        sev_map = {"High": 4, "Medium": 3, "Low": 2, "Informational": 1}
        sev_str = props.get("severity", "Low")
        return {
            "id": alert.get("name"),
            "display_name": props.get("alertDisplayName"),
            "description": props.get("description", ""),
            "severity": sev_map.get(sev_str, 1),
            "severity_label": sev_str.lower(),
            "status": props.get("status"),
            "provider": props.get("providerName"),
            "product": props.get("productName"),
            "start_time": props.get("startTimeUtc"),
            "end_time": props.get("endTimeUtc"),
            "processing_end_time": props.get("processingEndTime"),
            "techniques": props.get("techniques", []),
            "tactics": props.get("tactics", []),
            "_raw": alert,
        }
