"""
ctm_sak.export.transforms.edl
==============================

External Dynamic List (EDL) transform for next-generation firewalls.

Produces plain-text IOC lists consumed by:

* Palo Alto Networks (PAN-OS EDL, URL Filtering category)
* Fortinet FortiGate (External Block List)
* Check Point (External Intelligence Feed)
* Cisco Firepower (Security Intelligence)
* Any other NGFW that accepts a plain-text URL list

Output format
-------------
Each file is plain UTF-8 text with one IOC value per line.  Lines starting
with ``#`` are comments.  Empty lines are ignored.

Separate output files are produced per IOC type so the firewall can assign
each to the appropriate security policy::

    indicators-ipv4.txt     → IP/CIDR blocking rules
    indicators-domain.txt   → DNS sinkhole / URL filtering
    indicators-url.txt      → URL filtering / web proxy
    indicators-sha256.txt   → File blocking / DLP
    indicators-ipv6.txt     → IPv6 blocking rules
    indicators-email.txt    → Anti-spam / email gateway

Usage::

    from ctm_sak.export.transforms.edl import EDLTransform

    transform = EDLTransform(
        ioc_types=["ipv4", "domain", "url"],
        header_comment=True,
        defang=False,        # output MUST be clean (no [.] substitutions)
        max_per_file=100_000,
    )
    result = transform.transform(filtered_indicators)
    # result.payloads = {
    #   "indicators-ipv4.txt":   "# CTM-SAK EDL\\n1.2.3.4\\n...",
    #   "indicators-domain.txt": "# CTM-SAK EDL\\nevil.com\\n...",
    #   "indicators-url.txt":    "# CTM-SAK EDL\\nhttps://evil.com/path\\n...",
    # }
"""

from __future__ import annotations

import re
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Set, TYPE_CHECKING

from ctm_sak.export.base import ExportTransform, TransformResult

if TYPE_CHECKING:
    from ctm_sak.orm.base import STIXBase


# Pattern strings → IOC type keywords (in STIX pattern format)
_PATTERN_KEYWORDS: Dict[str, str] = {
    "ipv4":   "ipv4-addr",
    "ipv6":   "ipv6-addr",
    "domain": "domain-name",
    "url":    "url:",
    "email":  "email-addr",
    "md5":    "hashes.MD5",
    "sha1":   "hashes.SHA-1",
    "sha256": "hashes.SHA-256",
    "asn":    "autonomous-system",
}

# Regex to extract the value from a STIX pattern
_VALUE_RE = re.compile(r"=\s*'([^']+)'")

# Defanging/refanging patterns
_DEFANG_PATTERNS = [
    (re.compile(r'\[\.?\]'), '.'),       # [.] or [.]
    (re.compile(r'hxxp://'), 'http://'),
    (re.compile(r'hxxps://'), 'https://'),
    (re.compile(r'\[\.\]'), '.'),
]


def _refang(value: str) -> str:
    """Remove common defanging substitutions to restore clean IOC values."""
    for pattern, replacement in _DEFANG_PATTERNS:
        value = pattern.sub(replacement, value)
    return value.strip()


def _extract_value(pattern_str: str) -> Optional[str]:
    """Pull the quoted value from a STIX pattern string."""
    m = _VALUE_RE.search(pattern_str)
    return m.group(1) if m else None


def _detect_ioc_type(pattern_str: str) -> Optional[str]:
    """Detect IOC type from a STIX pattern string."""
    for ioc_type, keyword in _PATTERN_KEYWORDS.items():
        if keyword in pattern_str:
            return ioc_type
    return None


class EDLTransform(ExportTransform):
    """
    Produce firewall-ready EDL plain-text files from STIX Indicator objects.

    Non-indicator objects are silently skipped.

    Parameters
    ----------
    ioc_types : list of str, optional
        IOC types to include.  Subset of: ``"ipv4"``, ``"ipv6"``,
        ``"domain"``, ``"url"``, ``"sha256"``, ``"sha1"``, ``"md5"``,
        ``"email"``, ``"asn"``.
        Default: all supported types.
    filename_prefix : str
        Prefix for output filenames.  Default ``"indicators"``.
    header_comment : bool
        Include a ``# Generated by CTM-SAK ...`` comment at the top.
        Default ``True``.
    max_per_file : int
        Maximum entries per file.  Files are truncated if exceeded and
        the count is noted in ``metadata``.  Default ``500_000``.
    sort_output : bool
        Sort IOC values alphabetically within each file.  Default ``True``.
    combine : bool
        If ``True``, produce a single combined file (``indicators-all.txt``)
        instead of per-type files.  Default ``False``.
    deduplicate : bool
        Remove exact-duplicate values within each type bucket.  Default ``True``.

    Examples
    --------
    ::

        # Separate files per type (default)
        t = EDLTransform(ioc_types=["ipv4", "domain", "url"])

        # Single combined file
        t = EDLTransform(combine=True)

        # Palo Alto-specific: IPs only, sorted, max 100K
        t = EDLTransform(ioc_types=["ipv4", "ipv6"], max_per_file=100_000)
    """

    ALL_TYPES = list(_PATTERN_KEYWORDS.keys())

    def __init__(
        self,
        ioc_types: Optional[List[str]] = None,
        filename_prefix: str = "indicators",
        header_comment: bool = True,
        max_per_file: int = 500_000,
        sort_output: bool = True,
        combine: bool = False,
        deduplicate: bool = True,
    ):
        super().__init__(label="EDLTransform")
        if ioc_types:
            unknown = set(ioc_types) - set(self.ALL_TYPES)
            if unknown:
                raise ValueError(
                    f"EDLTransform: unknown IOC types {sorted(unknown)}. "
                    f"Valid: {sorted(self.ALL_TYPES)}"
                )
        self._ioc_types       = set(ioc_types) if ioc_types else set(self.ALL_TYPES)
        self._prefix          = filename_prefix
        self._header          = header_comment
        self._max             = max_per_file
        self._sort            = sort_output
        self._combine         = combine
        self._deduplicate     = deduplicate

    def transform(self, objects: List["STIXBase"]) -> TransformResult:
        """
        Extract IOC values from STIX Indicator objects and render EDL files.

        Parameters
        ----------
        objects : list of STIXBase
            All should be Indicator objects (others are skipped).

        Returns
        -------
        TransformResult
            ``payloads`` contains one entry per IOC type file.
            ``metadata`` contains per-type counts and any truncation warnings.
        """
        buckets: Dict[str, List[str]] = {t: [] for t in self._ioc_types}
        seen:    Dict[str, Set[str]]  = {t: set() for t in self._ioc_types}
        skipped = 0
        processed = 0

        for obj in objects:
            if obj.stix_type != "indicator":
                skipped += 1
                continue

            pattern_str = obj._properties.get("pattern", "")
            if not pattern_str and hasattr(obj, "pattern"):
                pattern_str = obj.pattern or ""

            ioc_type = _detect_ioc_type(pattern_str)
            if not ioc_type or ioc_type not in self._ioc_types:
                skipped += 1
                continue

            value = _extract_value(pattern_str)
            if not value:
                # Try the name field as fallback
                value = getattr(obj, "name", None) or obj._properties.get("name", "")
            if not value:
                skipped += 1
                continue

            value = _refang(value)

            if self._deduplicate:
                if value in seen[ioc_type]:
                    continue
                seen[ioc_type].add(value)

            buckets[ioc_type].append(value)
            processed += 1

        # Sort and cap
        metadata: Dict[str, Any] = {
            "processed": processed,
            "skipped":   skipped,
            "truncated": {},
        }
        for ioc_type in list(buckets.keys()):
            entries = buckets[ioc_type]
            if self._sort:
                entries.sort()
            if len(entries) > self._max:
                metadata["truncated"][ioc_type] = len(entries) - self._max
                entries = entries[: self._max]
                buckets[ioc_type] = entries

        # Build payloads
        header = self._build_header()
        payloads: Dict[str, str] = {}

        if self._combine:
            all_values: List[str] = []
            for t in sorted(self._ioc_types):
                all_values.extend(buckets[t])
            payloads[f"{self._prefix}-all.txt"] = header + "\n".join(all_values) + "\n"
        else:
            for ioc_type in sorted(self._ioc_types):
                entries = buckets[ioc_type]
                if not entries:
                    continue
                filename = f"{self._prefix}-{ioc_type}.txt"
                payloads[filename] = header + "\n".join(entries) + "\n"

        for ioc_type, entries in buckets.items():
            metadata[f"count_{ioc_type}"] = len(entries)

        return TransformResult(
            payloads=payloads,
            object_count=processed,
            metadata=metadata,
        )

    def _build_header(self) -> str:
        if not self._header:
            return ""
        now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        return (
            f"# Generated by CTM-SAK at {now}\n"
            f"# Types: {', '.join(sorted(self._ioc_types))}\n"
        )

    def __repr__(self) -> str:
        return (
            f"EDLTransform(types={sorted(self._ioc_types)}, "
            f"combine={self._combine}, max={self._max})"
        )
