name: Bandit

on:
  push:
  pull_request:

jobs:
  bandit:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Run Bandit
        uses: PyCQA/bandit-action@v1.0.1
        